resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [db-all:children]
    db01
    db02

    [nginx]
     ansible_host=${local.Foo}

    [db01]
    db01 ansible_host=${yandex_compute_instance.db01.hostname} 
    [db01:vars]
    ansible_user=ubuntu
    ansible_ssh_common_args='-o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@${local.Foo}"'

    [db02]
    db02 ansible_host=${yandex_compute_instance.db02.hostname} 
    [db02:vars]
    ansible_user=ubuntu
    ansible_ssh_common_args='-o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@${local.Foo}"'

    [app]
    app ansible_host=${yandex_compute_instance.app.hostname} 
    [app:vars]
    ansible_user=ubuntu
    ansible_ssh_common_args='-o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@${local.Foo}"'

    [gitlab]
    gitlab ansible_host=${yandex_compute_instance.gitlab.hostname}
    [gitlab:vars]
    ansible_user=ubuntu
    ansible_ssh_common_args='-o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@${local.Foo}"'

    [runner]
    runner ansible_host=${yandex_compute_instance.runner.hostname}
    [runner:vars]
    ansible_user=ubuntu
    ansible_ssh_common_args='-o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@${local.Foo}"'

    [monitoring]
    monitoring ansible_host=${yandex_compute_instance.monitoring.hostname}
    [monitoring:vars]
    ansible_user=ubuntu
    ansible_ssh_common_args='-o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@${local.Foo}"'
    DOC
  filename = "../ansible/inventory"

  depends_on = [
    yandex_compute_instance.db01,
    yandex_compute_instance.db02,
    yandex_compute_instance.maksam,
    yandex_compute_instance.app,
    yandex_compute_instance.gitlab,
    yandex_compute_instance.runner,
    yandex_compute_instance.monitoring
  ]
}
